theme: jekyll-theme-minimal
logo: /logo.png
title: "  "
github:
  is_project_page: false
  
layout: page
title: "feedback"
permalink: /https://github.com/ShaktiCV/Personal-Website/blob/main/feedback.md/
